lib: [
  "_build/install/default/lib/target/META"
  "_build/install/default/lib/target/dune-package"
  "_build/install/default/lib/target/opam"
  "_build/install/default/lib/target/target.a"
  "_build/install/default/lib/target/target.cma"
  "_build/install/default/lib/target/target.cmi"
  "_build/install/default/lib/target/target.cmt"
  "_build/install/default/lib/target/target.cmx"
  "_build/install/default/lib/target/target.cmxa"
  "_build/install/default/lib/target/target.ml"
]
libexec: [
  "_build/install/default/lib/target/target.cmxs"
]
doc: [
  "_build/install/default/doc/target/README.md"
]
